<?php

namespace HomeBundle\Repository;

/**
 * BricoleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BricoleurRepository extends \Doctrine\ORM\EntityRepository
{
}
